version: "3.8"
services:
  api:
    mem_limit: 12g
    cpus: 3
    build: .
    ports:
      - "8894:80" #localhost port : container exposed port
    working_dir: /app/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
